# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metalheartapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='spotify_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
