# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metalheartapp', '0002_auto_20171017_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonMetalArtist',
            fields=[
                ('spotify_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
